env:
 - GHCVER=7.8.3 CABALVER=1.20
 - GHCVER=7.8.4 CABALVER=1.22
 - GHCVER=7.10.1 CABALVER=1.22
 - GHCVER=head   CABALVER=1.22

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
 - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
 - travis_retry sudo apt-get update
 - sudo apt-get install qdbus qmlscene qt5-default qt5-qmake qtbase5-dev-tools qtchooser qtdeclarative5-dev xbitmaps libqt5svg5-dev qttools5-dev qtscript5-dev qtdeclarative5-controls-plugin -y
 - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER hlint happy-1.19.3 alex-3.1.3 c2hs
 - # The cabal packages from hvr's PPA are missing the Cabal library
 - cabal-$CABALVER install Cabal --constraint "Cabal ==$CABALVER.*" -j
 - cabal-$CABALVER update
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/1.19.3/bin:/opt/alex/3.1.3/bin:~/.cabal/bin:$PATH

install:
 - cabal-$CABALVER install --only-dependencies --enable-tests --enable-benchmarks -j

script:
 - travis/script.sh

matrix:
  allow_failures:
   - env: GHCVER=head CABALVER=1.22
  fast_finish: true