env:
 - GHCVER=7.8.3  CABALVER=1.18
 - GHCVER=7.8.4  CABALVER=1.18
 - GHCVER=7.10.1 CABALVER=1.22

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty universe"
 - sudo add-apt-repository "deb http://archive.ubuntu.com/ubuntu trusty main"
 - travis_retry sudo apt-get update
 - sudo apt-get install qdbus qmlscene qt5-default qt5-qmake qtbase5-dev-tools qtchooser qtdeclarative5-dev xbitmaps libqt5svg5-dev qttools5-dev qtscript5-dev qtdeclarative5-controls-plugin -y
 - sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER hlint happy-1.19.3 alex-3.1.3 c2hs
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:/opt/happy/1.19.3/bin:/opt/alex/3.1.3/bin:$PATH
 - cabal update

install:
 - | 
   if [ "$GHCVER" = "7.10.1" ]; then
     packages=$(mktemp -d)
     cd $packages

     cabal get pqueue; cd pqueue-*
     curl -L https://github.com/bumptech/haskell-pqueue/pull/2.patch | patch -p1
     cabal install
     cd ..;

     cd $TRAVIS_BUILD_DIR
     cabal install --only-dependencies --enable-tests --enable-benchmarks -j --allow-newer
   else
     cabal install --only-dependencies --enable-tests --enable-benchmarks -j
   fi

script:
 - travis/script.sh

matrix:
  fast_finish: true